# Generated by Django 3.0 on 2022-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('miniature', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField()),
                ('video', models.TextField(blank=True, null=True)),
                ('langue_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actualites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assemblees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=300, null=True)),
                ('ville_id', models.IntegerField()),
                ('localisation', models.TextField(blank=True, null=True)),
                ('addresse', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assemblees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cantiques',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('lien_audio', models.TextField()),
                ('nom_fichier', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cantiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChargeUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('assemblee_id', models.IntegerField(blank=True, null=True)),
                ('principal', models.TextField()),
                ('position_chantre', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charge_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concordances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verset_from_id', models.IntegerField()),
                ('verset_to_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concordances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Confirmes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('pays_id', models.IntegerField()),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'confirmes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=300, unique=True)),
                ('connection', models.TextField()),
                ('queue', models.TextField()),
                ('payload', models.TextField()),
                ('exception', models.TextField()),
                ('failed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'failed_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguePays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('langue_id', models.IntegerField()),
                ('pays_id', models.IntegerField()),
                ('principal', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'langue_pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Langues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=300, null=True)),
                ('initial', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'langues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('migration', models.CharField(blank=True, max_length=300, null=True)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_resets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=300, null=True)),
                ('sigle', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalAccessTokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tokenable_type', models.CharField(blank=True, max_length=300, null=True)),
                ('tokenable_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('token', models.CharField(max_length=300, unique=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_access_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('lieu', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=300, null=True)),
                ('sous_titre', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('lien_audio', models.TextField(blank=True, null=True)),
                ('nom_audio', models.TextField(blank=True, null=True)),
                ('lien_video', models.TextField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('chapitre', models.CharField(blank=True, max_length=300, null=True)),
                ('couverture', models.TextField(blank=True, null=True)),
                ('sermon_similaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'predications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField(blank=True, null=True)),
                ('lien_video', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temoignages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('telephone', models.CharField(blank=True, max_length=300, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('youtube', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Versets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('contenu', models.TextField()),
                ('info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'versets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('url', models.TextField()),
                ('lieu', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'videos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Villes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pays_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'villes',
                'managed': False,
            },
        ),
    ]
